apiVersion: v1
items:
- apiVersion: scheduling.k8s.io/v1beta1
  kind: PriorityClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"scheduling.k8s.io/v1beta1","kind":"PriorityClass","metadata":{"annotations":{},"creationTimestamp":"2019-08-14T21:58:26Z","generation":1,"name":"high-priority","resourceVersion":"14886069","selfLink":"/apis/scheduling.k8s.io/v1beta1/priorityclasses/high-priority"},"value":1000000}
    creationTimestamp: "2019-09-23T18:52:58Z"
    generation: 1
    name: high-priority
    resourceVersion: "1733081"
    selfLink: /apis/scheduling.k8s.io/v1beta1/priorityclasses/high-priority
    uid: 5c6a42b3-de33-11e9-bb74-42010a8001fc
  value: 1000000
- apiVersion: scheduling.k8s.io/v1beta1
  description: Used for system critical pods that must run in the cluster, but can
    be moved to another node if necessary.
  kind: PriorityClass
  metadata:
    creationTimestamp: "2019-09-17T19:12:13Z"
    generation: 1
    name: system-cluster-critical
    resourceVersion: "37"
    selfLink: /apis/scheduling.k8s.io/v1beta1/priorityclasses/system-cluster-critical
    uid: 0e3f0a15-d97f-11e9-bb1f-42010a800115
  value: 2000000000
- apiVersion: scheduling.k8s.io/v1beta1
  description: Used for system critical pods that must not be moved from their current
    node.
  kind: PriorityClass
  metadata:
    creationTimestamp: "2019-09-17T19:12:13Z"
    generation: 1
    name: system-node-critical
    resourceVersion: "36"
    selfLink: /apis/scheduling.k8s.io/v1beta1/priorityclasses/system-node-critical
    uid: 0e3b346f-d97f-11e9-bb1f-42010a800115
  value: 2000001000
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
